[tool.black]
line-length = 88
target-version = ['py310', 'py311']

[tool.isort]
atomic = true
profile = "black"

[tool.pylint.messages_control]
max-line-length = 88
disable = [
    "line-too-long",
    "missing-docstring",
    "no-else-return",
]

[tool.mypy]
mypy_path = "src"

# Import global settings
#disallow_any_unimported = true
ignore_missing_imports = true

# Stricter checking
disallow_untyped_defs = true
#disallow_untyped_calls = true
#strict_optional = true
warn_return_any = true
warn_no_return = true
#warn_redundant_casts = true
#warn_unreachable = true

# Meta-checking
show_error_codes = true
warn_unused_ignores = true
